import type {Metadata} from "next";
import '../globals.css';
import localFont from "next/font/local";
export const metadata: Metadata = {
    title: "Dimitris Sparagis",
    description: "Generated by create next app",
};


// @ts-ignore
export default function AboutLayout({children}) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.ico" sizes="any"/>
            <title></title>
        </head>

        <body className={`bg-gradient-to-r from-black to-gray-900`}>
            {children}
        </body>
        </html>
    );
}